version: '3.4'

services:
  bankapp:
    image: ${DOCKER_REGISTRY-}bankapp
    build:
      context: .
      dockerfile: BankApp/Dockerfile

  mssql-server:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
